# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test

on:
  workflow_dispatch:
    inputs:
      school:
        description: "Add your School name"
        required: true
        default: "Chaman lal dav"
      Department:
        description:  "Department"
        type: choice
        default: medical
        required: true
        options:
          - Science
          - commerce
          - medical
      Inermediate:
        type: boolean
        required: true
        default: true
      number:
        description: "Enter a number"
        type: number
        required: true
        
        
           
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: 'naman singh negi'
      roll_number: 12345
      class: "Tenth"
      password: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: My first Student info
        run:  echo "Your school name is ${{ inputs.school }} and your Department is ${{ inputs.Department }}, you are in ${{ inputs.Intermediate && '12' || '10' }}"

      - name: My env variables print
        run: |
          echo " your name is  $name  and your roll number is $roll_number  and  class is $class"

      - name: Printing Github Repo Varibales and Passwords
        run: |
          echo " your password is :  $password   and   your  Father name is :  ${{ vars.FATHER_NAME }}"


      - name: Checking for even and odd using $GITHUV_ENV
        id: check
        run: |
          num="${{ inputs.number }}"
          if [ $((num % 2)) -eq 0 ]; then
            echo "$num is even"
            echo "result=even" >> $GITHUB_ENV
          else
            echo "$num is odd"
            echo "result=odd" >> $GITHUB_ENV
          fi

      - name: Result of even and odd
        run: echo " Result is ${{ env.result }} "

      - name: Checking for $GITHUB_OUTPUT
        id: id_checking
        run: echo "version=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Using the Github OUTPUT in this step
        run: echo " APP version is ${{ steps.id_checking.outputs.version }}"


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Using the Github output from above job
        run: echo "Deploying version: ${{ needs.build.outputs.version }} "

      
         
      
          
   







