name: Test

on:
  workflow_dispatch:
    inputs:
      school:
        description: "Add your School name"
        required: true
        default: "Chaman lal dav"
      Department:
        description: "Department"
        type: choice
        default: medical
        required: true
        options:
          - Science
          - commerce
          - medical
      Intermediate:            # fixed spelling (was "Inermediate")
        type: boolean
        required: true
        default: true
      number:
        description: "Enter a number"
        type: number
        required: true
      environment:
        type: string
        required: true
        default: prod

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: "naman singh negi"
      roll_number: 12345
      class: "Tenth"
      password: ${{ secrets.PASSWORD }}

    outputs:
      version: ${{ steps.id_checking.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: My first Student info
        run: |
          echo "Your school name is ${{ inputs.school }} and your Department is ${{ inputs.Department }}, you are in ${{ inputs.Intermediate && '12' || '10' }}"

      - name: My env variables print
        run: |
          echo "Your name is $name, roll number is $roll_number, class is $class"

      - name: Printing Github Repo Variables and Passwords
        run: |
          echo "Your password is: $password and your Father name is: ${{ vars.FATHER_NAME }}"

      - name: Checking for even and odd using $GITHUB_ENV
        id: check
        run: |
          num="${{ inputs.number }}"
          if [ $((num % 2)) -eq 0 ]; then
            echo "$num is even"
            echo "result=even" >> $GITHUB_ENV
          else
            echo "$num is odd"
            echo "result=odd" >> $GITHUB_ENV
          fi

      - name: Result of even and odd
        run: echo "Result is ${{ env.result }}"

      - name: Checking for $GITHUB_OUTPUT
        id: id_checking
        run: echo "version=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Using the Github OUTPUT in this step
        run: echo "APP version is ${{ steps.id_checking.outputs.version }}"

                # 👈 Moved under jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Using the Github output from above job
        run:  |
          echo "Deploying version: ${{ needs.build.outputs.version }}"

      - name: Calling Resuable workflow
        uses: NamanSinghNegi/sample-prject/.github/workflows/reusbale-workflow.yaml@dev
        with:
          environment: ${{ inputs.environment }}



